# Generated by Django 5.2 on 2025-05-24 18:19

from django.db import migrations
from django.utils.text import slugify

def update_tag_slugs(apps, schema_editor):
    Tag = apps.get_model('projects', 'Tag')
    for tag in Tag.objects.all():
        if not tag.slug:
            tag.slug = slugify(tag.name)
            tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(update_tag_slugs),
    ]
